version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  bot:
    build: .
    container_name: bot
    depends_on:
      - redis
    restart: always